### ISSUE TITLE
More SBATCH/SRUN options

### ISSUE THREAD

**Issue by victorsndvg** [MSO4SC/cloudify-hpc-plugin#4]
Hi Javier,

this is an examples sbatch script to run a Paraview server at FT2. This is an alternative to get remote visualization without the need of serving a remote desktop.

```
#SBATCH -p shared
#SBATCH --qos=shared
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 00:30:00
#SBATCH --mem=32GB
#SBATCH --mail-user=your@mailes
#SBATCH --mail-type=ALL

module load ParaView/5.0.1

srun --mpi=pmi2 pvserver --use-offscreen-rendering --server-port=11111 > ParaView_pvserver.log 2>&1
```

It contains several SBATCH job configuration flags. It could be interesting to have them implemented in the orchestrator.

What do you think?

**Comment by Trophime** [comment]
That would be great indeed.
By the way, would it be also possible to have only
```
#SBATCH --ntasks=m
```
with ntasks being defined via `parralel_tasks` in input and equivalent values for nodes and/or tasks/node are not defined?

**Comment by emepetres** [comment]
@Trophime the answer is yes, we are already doing that in OPM Flow, check its blueprint.
@victorsndvg please answer with exactly the missing options in srun/sbatch you would like to add.

**Comment by Trophime** [comment]
@emepetres we would like:
```
#SBATCH --mail-user=your@mailes
#SBATCH --mail-type=ALL
#SBATCH --mem=32GB
```

**Comment by victorsndvg** [comment]
I agree :+1: 

I think the expected behaviour should be: If they option exist in the blueprint apply to the sbatch script or sreun command ( add --flag value ), If not don't add it

I think we can live without having this options implemented for the review (my point of view)
