### ISSUE TITLE
High performance data transfers

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/cloudify-hpc-plugin#53]
Movement of large datasets efficiently, and integrated in the portal.

**Comment by victorsndvg** [comment]
- Understand end-user interaction with globusonline.
    [x] End point creation and configuration
    - Personal accounts:
         [x] OAuth integration with globus: not free
         [x] Other altenatives: OpenID, etc.
     - Integrate globus CLI with workflows
         [x] Requirements: Credentials and endpoint references
         [x] User interaction and configuration: Globus docs
         [x] Globus-CLI containerization: done
     - Integrate with sRegistry: Needs premium account
         [x] My-endpoints + shared-with-me endpoints
         [x] Integrated with globusonline
     - Blueprints
         [x] globus as an alternative (+ rclone, + wget, etc.) Manage several alternatives based on protocol
     - Best practices:
         [x] Avoid downloads if things are located in the right place and ready to be used
