### ISSUE TITLE
Atlas integration

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/cloudify-hpc-plugin#58]
Connection to Atlas is not currently possible due to:
- Direct connection to atlas through ssh is only possible on 131 through key pair authentication, while the orchestrator is only using password (#56)
- There is a possibility to connect by another ssh machine. "SSH proxy" or tunnel is necessary in this case (#57)

**Comment by Trophime** [comment]
:+1:

**Comment by emepetres** [comment]
All tests are passing in Atlas (except singularity which I think you don't have installed)! @gdolle I need you to review this and confirm that Atlas integration is working.

To test, you will need to use the canary version of the plugin (import the plugin from canary branch instead of master), and modify your blueprints with the new ssh options (see README).

**Comment by prudhomm** [comment]
@vincentchabannes it seems that atlas is now available in the canary version. Could you check that it is indeed ok ?
