### ISSUE TITLE
New flag '--res' for SBATCH based job types

### ISSUE THREAD

**Issue by victorsndvg** [MSO4SC/cloudify-hpc-plugin#6]
Hi @emepetres ,

due to the recent resources reservations, now we have a new flag for SBATCH job types (and all those job types relying on SBATCH). I think we should enable the Orchestrator to use this flag.

This flag is `--res`.

Here I partially paste the email talking about this flag:

> Dear all,
> 
> we have reserved 2 nodes (48 cores) of "thinnodes" partition at FT2 for MSO4SC project until the end of the review (2018-01-26).
Please, note that if your job exceed those resources (2 nodes, 48 cores), you must not use this reservation.
> 
> To use the reserved resources, you have to assign "MSO4SC" to the reservation flag ( "--res=MSO4SC" ) for the Slurm command.

> E.g:
>   $ sbatch --res=MSO4SC ...
>   $ squeue --res=MSO4SC ...
>   $ scontrol show res=MSO4SC
> ...

**Comment by emepetres** [comment]
In Slurm docs there is no metion of `--res=<name>` option. Instead talks about `--reservation=<name>`. What property should I implement in the orchestrator?

**Comment by victorsndvg** [comment]
Hi @emepetres ,

yes you are right official documentation talks about `--reservation`.

I asked about it and my colleagues answer me that both are equivalent. You can choose whatever you want, but as you said `--reservation` appears in docs and maybe it's better to use this option for ensuring forward compatibility. Do you agree?
