### ISSUE TITLE
Cloudify plugin for IM

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/cloudify-hpc-plugin#61]
The plugin will support creation/remove of VMs through the IM, and sending ssh commands to them (jobs).

It will have to monitor the jobs somehow.

Depends on #59

**Comment by victorsndvg** [comment]
As an alternative we can think in an Cloudify+OCCI plugin:
- http://internal-wiki.west-life.eu/index.php/WP4_Portal_Virtualization
- https://github.com/ICS-MU/westlife-cloudify-occi-plugin

Pros:
- Already implemented. We only need to learn to use it
Cons:
- Less generic support for heterogeneous Cloud providers

To think
