### ISSUE TITLE
feature request: add a post step

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/cloudify-hpc-plugin#75]
Would it be possible to have the same kind of `-pre` feature that @victorsndvg implemented for monitoring for post-processing?

Typical use case would be:
* to create a gzipped tarball of the results to be uploaded to CKAN
* to generate an image (a 1D/2D plot)

**Comment by victorsndvg** [comment]
Maybe @emepetres can add more details here. 

He was the one who implement the `pre` command list, but also a `post` command list after the _heavy_ simulation command and inside the _sbatch_ script.

@Trophime , maybe this option already solves your requirements?

**Comment by Trophime** [comment]
I was not aware of that command.
Is there some examples of the `post` command?

**Comment by victorsndvg** [comment]
There are no example. The usage is the same as the `pre`  option. A list of shell commands to be executed befor(pre)/after(post) the __command__. 

Here is in the docs:
https://github.com/MSO4SC/cloudify-hpc-plugin/tree/canary#hpcnodessingularityjob

You can take the `pre` example here:
https://github.com/MSO4SC/resources/blob/master/blueprint-examples/single-singularity-logger/blueprint.yaml#L71

If you need I can update a blueprint-example to include the `post` feature

**Comment by Trophime** [comment]
thanks 👍

**Comment by victorsndvg** [comment]
@Trophime , finally I found where it is implemented:

https://github.com/MSO4SC/cloudify-hpc-plugin/blob/canary/hpc_plugin/workload_managers/slurm.py#L66

Note that only `SingularityJob`s support it!
